// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import { getSupabaseConfig } from "@/lib/runtimeConfig";
import type { Database } from "./types";

const { url, publishableKey, isConfigured } = getSupabaseConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = isConfigured
  ? createClient<Database>(url!, publishableKey!, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : null;
